# TUTORIAL 3

In [23]:
import numpy as np
from pprint import pp

In [27]:

class LinalgSolve():
    def __init__(self, A, b) -> None:
        self.A = np.array(A)
        self.b = np.array(b)
        self.n = len(self.A)
        self.I = [[0] * i + [1] + [0] * (self.n - i - 1) for i in range(self.n)]


    def GJElimination(self):  # speed : N^3
        return
    
    def GaussEleminiation(self, ): #similar to GJ but pivots are not scaled to 1. Reducde to 0 below diagonal
        return
    
    def LUDecomposition(self): #speed : (1/3)N^3 but solving for new b is N^2
        return
     

In [31]:
A=np.array([[1,2,4],[3,4,5],[1,2,4]])
b= [1,2,5]


[[1 2 4]
 [3 4 5]
 [1 2 4]]
